version: '3'

services:
  database:
    image: 'mongo'
    container_name: 'mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=Connections
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'

  db-exporter :
     image :  bitnami/mongodb-exporter:0.11
     environment :
      -  MONGODB_URI=mongodb://localhost:27017
      - MONGO_INITDB_DATABASE=Connections
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
     restart :  always
     ports : 
      -  9216:9216
  api:
    build: ./api
    ports:
      - 5000:3000
  frontend:
    build: ./frontend
    ports:
      - 4000:4000 
    depends_on:
      - api
  prometheus:
      image: prom/prometheus:latest
      volumes:
        - ./prometheus:/etc/prometheus
        - prometheus-data:/prometheus
      ports:
        - 9090:9090
      command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    build: ./grafana
    ports: 
      - 3000:3000

volumes:
  mongo-volume:
  prometheus-data: 

  